# примеры API-запросов

@baseUrl = https://localhost:8000/api

### получение объявлений - done
GET {{baseUrl}}/advertisements/
Content-Type: application/json

### создание объявления - done
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 05fbee61cfa6d2b96d95eee46cbbbf1494f92be3

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

### создание объявления #2 от другого пользователя
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8cef65f70101a86a4036b660d9a2f1d53fd0e728

{
  "title": "Объявление №10",
  "description": "От пользователя №2"
}

### попытка создания объявления без токена
POST {{baseUrl}}/advertisements/
Content-Type: application/json

{
  "title": "Объявление без токена",
  "description": "Нет токена"
}

### TODO: попытка поменять объявление - done
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
#Authorization: Token 05fbee61cfa6d2b96d95eee46cbbbf1494f92be3
Authorization: Token 8cef65f70101a86a4036b660d9a2f1d53fd0e728

{
  "status": "CLOSED"
}

### фильтрация по создателю - done
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

### фильтрация по дате - done
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
